baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'ChenKui164 blogs test'

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1
